"""
TIA (Target Item Analysis) detection -- simplified version from Huang et al.
Key insight: fake users generated by DLAttack have unusually concentrated
interactions on the target item + items with high embedding similarity.
Detects fake users by anomaly scoring based on:
  1. Fraction of interactions that are with "popular neighbors" of target item

Accepts either a plain TwoTower or a TwoTowerTrainTask.
"""
import numpy as np
import pandas as pd
import torch
def _unwrap(model):
    """Unwrap TrainTask wrapper to get the inner model, or return as-is."""
    if hasattr(model, "two_tower"):
        return model.two_tower
    if hasattr(model, "dlrm"):
        return model.dlrm
    return model


def compute_user_anomaly_scores(
    train_df: pd.DataFrame,
    model,
    target_item_id: int,
    n_items: int,
    top_similar: int = 50,
) -> pd.Series:
    """
    For each user, compute an anomaly score based on:
      - What fraction of their interactions are with items similar to target_item?
    Higher score -> more likely to be a fake user injected by DLAttack.
    """
    two_tower = _unwrap(model)

    with torch.no_grad():
        item_embs = two_tower.get_item_embeddings()
        target_emb = item_embs[target_item_id]
        sims = torch.nn.functional.cosine_similarity(
            item_embs, target_emb.unsqueeze(0)
        ).cpu().numpy()
    sim_items = set(np.argsort(sims)[-top_similar:].tolist())

    scores = {}
    for uid, group in train_df.groupby("user_id"):
        items = set(group["item_id"].tolist())
        overlap = len(items & sim_items) / max(len(items), 1)
        scores[uid] = overlap

    return pd.Series(scores)


def detect_fake_users(
    train_df: pd.DataFrame,
    model,
    target_item_id: int,
    n_items: int,
    threshold_percentile: float = 95.0,
) -> set:
    """
    Returns set of user IDs flagged as fake (anomaly score above threshold).
    """
    scores = compute_user_anomaly_scores(train_df, model, target_item_id, n_items)
    threshold = np.percentile(scores.values, threshold_percentile)
    flagged = set(scores[scores >= threshold].index.tolist())
    print(f"  Threshold (p{threshold_percentile}): {threshold:.4f}")
    print(f"  Flagged {len(flagged)} users out of {len(scores)}")
    return flagged
